// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace fitmongerdb.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20260310022440_articletypes")]
    partial class articletypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Article", b =>
                {
                    b.Property<int>("ArticleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleID"));

                    b.Property<int>("ArticleTypeID")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DateAquired")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateLastWorn")
                        .HasColumnType("date");

                    b.Property<string>("Material")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char?>("Size")
                        .HasColumnType("character(1)");

                    b.HasKey("ArticleID");

                    b.HasIndex("ArticleTypeID");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("ArticleType", b =>
                {
                    b.Property<int>("ArticleTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArticleTypeID"));

                    b.Property<int?>("BodyRegionID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArticleTypeID");

                    b.HasIndex("BodyRegionID");

                    b.ToTable("ArticleTypes");

                    b.HasData(
                        new
                        {
                            ArticleTypeID = 1,
                            BodyRegionID = 2,
                            Name = "Shirt"
                        },
                        new
                        {
                            ArticleTypeID = 2,
                            BodyRegionID = 3,
                            Name = "Pants"
                        },
                        new
                        {
                            ArticleTypeID = 3,
                            BodyRegionID = 4,
                            Name = "Shoes"
                        },
                        new
                        {
                            ArticleTypeID = 4,
                            BodyRegionID = 1,
                            Name = "Hat"
                        },
                        new
                        {
                            ArticleTypeID = 5,
                            BodyRegionID = 5,
                            Name = "Gloves"
                        },
                        new
                        {
                            ArticleTypeID = 6,
                            BodyRegionID = 6,
                            Name = "Scarf"
                        },
                        new
                        {
                            ArticleTypeID = 7,
                            BodyRegionID = 7,
                            Name = "Jacket"
                        },
                        new
                        {
                            ArticleTypeID = 8,
                            BodyRegionID = 8,
                            Name = "Socks"
                        },
                        new
                        {
                            ArticleTypeID = 9,
                            BodyRegionID = 9,
                            Name = "Watch"
                        });
                });

            modelBuilder.Entity("BodyRegion", b =>
                {
                    b.Property<int>("BodyRegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BodyRegionID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BodyRegionID");

                    b.ToTable("BodyRegions");

                    b.HasData(
                        new
                        {
                            BodyRegionID = 1,
                            Name = "Head"
                        },
                        new
                        {
                            BodyRegionID = 2,
                            Name = "Torso"
                        },
                        new
                        {
                            BodyRegionID = 3,
                            Name = "Legs"
                        },
                        new
                        {
                            BodyRegionID = 4,
                            Name = "Feet"
                        },
                        new
                        {
                            BodyRegionID = 5,
                            Name = "Arms"
                        },
                        new
                        {
                            BodyRegionID = 6,
                            Name = "Neck"
                        },
                        new
                        {
                            BodyRegionID = 7,
                            Name = "Upper Torso"
                        },
                        new
                        {
                            BodyRegionID = 8,
                            Name = "Shins"
                        },
                        new
                        {
                            BodyRegionID = 9,
                            Name = "Wrist"
                        });
                });

            modelBuilder.Entity("Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("Article", b =>
                {
                    b.HasOne("ArticleType", "ArticleType")
                        .WithMany()
                        .HasForeignKey("ArticleTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArticleType");
                });

            modelBuilder.Entity("ArticleType", b =>
                {
                    b.HasOne("BodyRegion", "BodyRegion")
                        .WithMany()
                        .HasForeignKey("BodyRegionID");

                    b.Navigation("BodyRegion");
                });
#pragma warning restore 612, 618
        }
    }
}
